"""initial schema

Revision ID: 4a57d4ec8295
Revises: 
Create Date: 2026-08-22 13:20:50.623058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a57d4ec8295'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('continente', sa.String(length=60), nullable=False),
    sa.Column('pais_principal', sa.String(length=120), nullable=False),
    sa.Column('paises_json', sa.Text(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('inicio_aproximado', sa.String(length=20), nullable=False),
    sa.Column('muertes_acumuladas', sa.Integer(), nullable=True),
    sa.Column('muertes_recientes', sa.Integer(), nullable=True),
    sa.Column('fuente_url', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('agent_order', sa.Integer(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_traces_evento_id'), ['evento_id'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.String(length=64), nullable=False),
    sa.Column('consensus_cluster_id', sa.String(length=64), nullable=False),
    sa.Column('causa_raiz', sa.Text(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('nivel_confianza', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('information_cutoff', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_evento_id'), ['evento_id'], unique=False)

    op.create_table('consensus_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('resumen_evento', sa.Text(), nullable=False),
    sa.Column('diversidad_institucional', sa.Integer(), nullable=False),
    sa.Column('puntuacion_confianza', sa.Float(), nullable=False),
    sa.Column('apto_para_analisis', sa.Boolean(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consensus_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consensus_events_cluster_id'), ['cluster_id'], unique=True)

    op.create_table('product_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=120), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('ticker_validacion', sa.String(length=20), nullable=False),
    sa.Column('comparador', sa.String(length=4), nullable=False),
    sa.Column('valor_umbral', sa.Float(), nullable=False),
    sa.Column('valor_base_al_emitir', sa.Float(), nullable=True),
    sa.Column('fecha_limite_revision', sa.String(length=20), nullable=False),
    sa.Column('probabilidad', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('information_cutoff', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resultado_valor_real', sa.Float(), nullable=True),
    sa.Column('evaluado_en', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_predictions_status'), ['status'], unique=False)

    op.create_table('system_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_runs_run_type'), ['run_type'], unique=False)

    op.create_table('event_causal_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=255), nullable=False),
    sa.Column('relacion', sa.String(length=120), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('causal_priors_version', sa.String(length=30), nullable=False),
    sa.Column('justificacion_aplicacion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('ticker_validacion', sa.String(length=20), nullable=False),
    sa.Column('comparador', sa.String(length=4), nullable=False),
    sa.Column('valor_umbral', sa.Float(), nullable=False),
    sa.Column('valor_base_al_emitir', sa.Float(), nullable=True),
    sa.Column('fecha_limite_revision', sa.String(length=20), nullable=False),
    sa.Column('probabilidad', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('information_cutoff', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resultado_valor_real', sa.Float(), nullable=True),
    sa.Column('evaluado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_status'))

    op.drop_table('predictions')
    op.drop_table('event_causal_links')
    with op.batch_alter_table('system_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_runs_run_type'))

    op.drop_table('system_runs')
    with op.batch_alter_table('product_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_predictions_status'))

    op.drop_table('product_predictions')
    with op.batch_alter_table('consensus_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consensus_events_cluster_id'))

    op.drop_table('consensus_events')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_evento_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_traces_evento_id'))

    op.drop_table('agent_traces')
    op.drop_table('active_conflicts')
    # ### end Alembic commands ###
