"""institutional governance layer: auth, audit log, review workflow, model inventory, kill switch

Revision ID: 9970e1c5fdfa
Revises: 4a57d4ec8295
Create Date: 2026-08-22 15:35:32.028722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9970e1c5fdfa'
down_revision: Union[str, Sequence[str], None] = '4a57d4ec8295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_email'), ['actor_email'], unique=False)

    op.create_table('model_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role_in_chain', sa.String(length=120), nullable=False),
    sa.Column('module_path', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('known_limitations', sa.Text(), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('last_independent_validation', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_cards_name'), ['name'], unique=True)

    op.create_table('system_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predictions_publishing_enabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_by', sa.String(length=255), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('model_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('prompt_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=False, server_default=sa.text("'PENDING_REVIEW'")))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.alter_column('probabilidad',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('model_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('prompt_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.create_index(batch_op.f('ix_predictions_review_status'), ['review_status'], unique=False)

    with op.batch_alter_table('product_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=False, server_default=sa.text("'PENDING_REVIEW'")))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.alter_column('probabilidad',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('model_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('prompt_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.create_index(batch_op.f('ix_product_predictions_review_status'), ['review_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_predictions_review_status'))
        batch_op.alter_column('prompt_version',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('model_version',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('probabilidad',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review_status')

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_review_status'))
        batch_op.alter_column('prompt_version',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('model_version',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('probabilidad',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review_status')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('prompt_version',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('model_version',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('system_control')
    with op.batch_alter_table('model_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_cards_name'))

    op.drop_table('model_cards')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_email'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
