"""Alias en espanol (y variantes comunes) hacia las claves canonicas de
`geo/country_centroids.py`. El LLM que genera `MacroAnalysis.ubicacion` o `ProductForecast`
puede nombrar un pais en espanol ("Libano", "Rusia") mientras que el catalogo de centroides usa
nombres en ingles; muchos pares ES/EN no son lo bastante parecidos como para que una
coincidencia difusa (fuzzy match) los detecte por si sola (ej. 'Libano' vs 'Lebanon'), asi que
se listan explicitamente los mas relevantes para conflictos y analisis geopolitico. Ver
`geo/geocode.py`.
"""
from __future__ import annotations

# alias (en minusculas, sin acentos) -> clave canonica en COUNTRY_CENTROIDS
COUNTRY_ALIASES: dict[str, str] = {
    "libano": "Lebanon",
    "rusia": "Russia",
    "ucrania": "Ukraine",
    "bielorrusia": "Belarus",
    "iran": "Iran",
    "irak": "Iraq",
    "arabia saudita": "Saudi Arabia",
    "arabia saudi": "Saudi Arabia",
    "emiratos arabes unidos": "United Arab Emirates",
    "egipto": "Egypt",
    "turquia": "Turkey",
    "siria": "Syria",
    "jordania": "Jordan",
    "birmania": "Myanmar",
    "tailandia": "Thailand",
    "filipinas": "Philippines",
    "sudan del sur": "South Sudan",
    "republica democratica del congo": "Democratic Republic of the Congo",
    "congo": "Democratic Republic of the Congo",
    "etiopia": "Ethiopia",
    "kenia": "Kenya",
    "camerun": "Cameroon",
    "niger": "Niger",
    "argelia": "Algeria",
    "libia": "Libya",
    "marruecos": "Morocco",
    "tunez": "Tunisia",
    "ruanda": "Rwanda",
    "mexico": "Mexico",
    "peru": "Peru",
    "brasil": "Brazil",
    "haiti": "Haiti",
    "azerbaiyan": "Azerbaijan",
    "palestina": "Palestine",
    "estados unidos": "United States",
    "eeuu": "United States",
    "ee.uu.": "United States",
    "reino unido": "United Kingdom",
    "gran bretana": "United Kingdom",
    "francia": "France",
    "alemania": "Germany",
    "italia": "Italy",
    "espana": "Spain",
    "paises bajos": "Netherlands",
    "belgica": "Belgium",
    "suiza": "Switzerland",
    "austria": "Austria",
    "polonia": "Poland",
    "suecia": "Sweden",
    "noruega": "Norway",
    "finlandia": "Finland",
    "dinamarca": "Denmark",
    "grecia": "Greece",
    "chipre": "Cyprus",
    "irlanda": "Ireland",
    "islandia": "Iceland",
    "kazajistan": "Kazakhstan",
    "uzbekistan": "Uzbekistan",
    "turkmenistan": "Turkmenistan",
    "kirguistan": "Kyrgyzstan",
    "mongolia": "Mongolia",
    "vietnam": "Vietnam",
    "camboya": "Cambodia",
    "singapur": "Singapore",
    "sudafrica": "South Africa",
    "ghana": "Ghana",
    "zimbabue": "Zimbabwe",
    "chile": "Chile",
    "cuba": "Cuba",
    "panama": "Panama",
    "republica dominicana": "Dominican Republic",
    "nueva zelanda": "New Zealand",
    "canada": "Canada",
    "australia": "Australia",
    "japon": "Japan",
    "taiwan": "Taiwan",
    "corea del sur": "South Korea",
    "corea del norte": "North Korea",
}
